AdityaTD/PenguBot

- commands/fun/trump.js
- commands/utilities/afk.js
Changed the names (Trump, trumpquote and etc). Also updated usage.
:P
> Fewer characters = good.

- commands/Utilities/translate.js
- package.json
> Translate Command

- README.md
It changes my contributor thing in the README.md
- Changed my contributor thing
> Change my contributer thingy

- commands/Music/queue.js
- lib/music/MusicInterface.js
- lib/structures/PenguClient.js
What does your pull request specfically does by adding/modifying or removing code?
Just see https://github.com/AdityaTD/PenguBot/pull/23
https://uwu.whats-th.is/aa453f.png
> Quantum's Full Voice "Upgrade"

- commands/Games/clashofclans
- languages/en-US.js
This PR adds a new command to check Clash of Clans stats.
- Add CoC stats.
> Clash of Clans command

- package.json
> fix: pin eslint to 5.0.0

- arguments/songname.js
- commands/Music/play.js
- lib/structures/LavalinkClient.js
- lib/structures/MusicInterface.js
This will allow the bot to search tracks on the LavalinkNode it's connected to. This does require all the node's REST port to be `2444` though.
- Change Player#getSongs
- Change play.js command
- Change songname.js argument
> Enhancement: getSongs() to use Lavalink Nodes

- README.md
Just updates Readme.md To Update The Guid Size Of Pengu from 23k => 25k
- No Changes, Just Changes in Readme.md.
-[ ] - This PR Updates readme.md
> 23k => 25k

- arguments/membername.js
And fixed many places where "user" is used in the place of a member
> fix: resolveUser -> resolveMember

- commands/Admin/setgame.js
Changes nothing of expected output, just removes useless code.
> this is done implicitly with await

- commands/Utilities/emote.js
Adds an emote command with the alias of emoji.
> feat: emote command

- commands/Utilities/quote.js
Enhances the current quote command to quote messages from different channels.
> better quote command

- commands/Games/rps.js
- commands/Games/slots.js
- commands/General/Admin/disablecmd.js
- commands/General/Admin/disablegroup.js
- commands/Jokes and Stuff/yomomma.js
- commands/Management/Logging/log.js
- commands/Management/Starboard/starboardchannel.js
- commands/Management/Starboard/starsrequired.js
- commands/Management/Starboard/togglestarboard.js
- commands/Moderation/ban.js
- commands/Moderation/mute.js
- commands/Moderation/prune.js
- commands/Moderation/softban.js
- commands/Moderation/toggleinvites.js
- commands/Utilities/afk.js
- languages/en-US.js
Converts majority of strings for i18n into the language file.
- Transfer majority of sentences to the language file.
- Change all emotes to the constant client value.
> Emotes and i18n

- arguments/songname.js
Fixing duped code in the regex for you. No point in running the same operation if its almost the same URL.
- Minimize duplicated code in songname.js
> Optimization: songname argument

- commands/Music/volume.js
- languages/en-US.js
- lib/structures/LavalinkClient.js
- lib/structures/MusicInterface.js
- lib/structures/schemas/defaultGuildSchema.js
- package.json
With the help of Jacz I have added Load Balanced Lavalink Music instead of Region Based. This requires further testing so it's on hold for review + testing.
- Update songname and musicinterface
> Music: Load Balanced Lavalink Music

- package.json
> fix(package): update @discordjs/uws to version 11.149.1

- commands/Music/loop.js
Allows a user to choose to loop through the whole queue.
> feat: queue-loop

- commands/Music/nowplaying.js
> added known aliases

- languages/fr-FR.js
Fixed 'default' key-error translation
> fixed: ER_CURR_LANG

- package.json
> fix(package): update hot-shots to version 6.1.1

- .gitignore
- src/PenguBot.js
- src/arguments/songname.js
- src/commands/Game Statistics/clashofclans.js
- src/commands/Game Statistics/clashroyale.js
- src/commands/Game Statistics/csgo.js
- src/commands/Game Statistics/fortnite.js
- src/commands/Music/loop.js
- src/commands/Music/play.js
- src/commands/Music/volume.js
- src/commands/Utilities/twstats.js
- src/commands/Utilities/weather.js
- src/commands/Utilities/ytstats.js
- src/events/guildCreate.js
- src/events/klasaReady.js
- src/functions/clearPatrons.js
- src/index.js
- src/inhibitors/patronOnly.js
- src/inhibitors/upvoterOnly.js
- src/lib/structures/MusicInterface.js
- src/lib/structures/PenguClient.js
- src/main.js
- src/monitors/perspectivemod.js
- src/routes/dblHook.js
- src/tasks/cleanGuilds.js
- src/tasks/dbl.js
- src/tasks/spotify.js
Removed the config from client.
Rewrite config file to js from json
- Removed the config from client.
-Rewrite config file to js from json.
- [] This PR adds methods, features, commands or properties
> Refactor(Config): Remove from client, json to js

- package.json
- src/arguments/songname.js
- src/commands/Music/dmsong.js
- src/commands/Music/dump.js
- src/commands/Music/loop.js
- src/commands/Music/music.js
- src/commands/Music/nowplaying.js
- src/commands/Music/play.js
- src/commands/Music/queue.js
- src/commands/Music/shuffle.js
- src/commands/Music/skip.js
- src/commands/Music/toggledj.js
- src/commands/Music/togglepause.js
- src/commands/Music/volume.js
- src/events/klasaReady.js
- src/inhibitors/requireMusic.js
- src/languages/en-US.js
- src/languages/es-ES.js
- src/languages/fr-FR.js
- src/languages/it-IT.js
- src/languages/sar-IT.js
- src/lib/structures/LavalinkClient.js
- src/lib/structures/MusicCommand.js
- src/lib/structures/MusicInterface.js
Getting ready for v3 of discord.js-lavalink
> [WIP]: Lavalink v3

- package.json
- src/arguments/songname.js
- src/commands/Music/dmsong.js
- src/commands/Music/dump.js
- src/commands/Music/loop.js
- src/commands/Music/music.js
- src/commands/Music/nowplaying.js
- src/commands/Music/play.js
- src/commands/Music/queue.js
- src/commands/Music/shuffle.js
- src/commands/Music/skip.js
- src/commands/Music/toggledj.js
- src/commands/Music/togglepause.js
- src/commands/Music/volume.js
- src/events/klasaReady.js
- src/inhibitors/requireMusic.js
- src/languages/en-US.js
- src/languages/es-ES.js
- src/languages/fr-FR.js
- src/languages/it-IT.js
- src/languages/sar-IT.js
- src/lib/structures/LavalinkClient.js
- src/lib/structures/MusicCommand.js
- src/lib/structures/MusicInterface.js
> Revert "[WIP]: Lavalink v3"

- package.json
- src/arguments/songname.js
- src/commands/Music/dmsong.js
- src/commands/Music/dump.js
- src/commands/Music/loop.js
- src/commands/Music/music.js
- src/commands/Music/nowplaying.js
- src/commands/Music/play.js
- src/commands/Music/queue.js
- src/commands/Music/shuffle.js
- src/commands/Music/skip.js
- src/commands/Music/toggledj.js
- src/commands/Music/togglepause.js
- src/commands/Music/volume.js
- src/events/klasaReady.js
- src/inhibitors/requireMusic.js
- src/languages/en-US.js
- src/languages/es-ES.js
- src/languages/fr-FR.js
- src/languages/it-IT.js
- src/languages/sar-IT.js
- src/lib/structures/LavalinkClient.js
- src/lib/structures/MusicCommand.js
- src/lib/structures/MusicInterface.js
> Lavalink v3

- src/commands/Music/stop.js
Fixed one sentence
- Edited one sentence in stop.js
> Fixing sentence in stop.js

- package.json
- src/extendables/prompt.js
- src/lib/structures/KlasaCommand.js
- src/lib/structures/MusicCommand.js
- src/lib/structures/permissionLevels.js
- src/main.js
Switch over to the v1.0.0-alpha branch for klasa.
> Move over to v1.0.0-alpha branch

- src/languages/en-US.js
- src/languages/es-ES.js
- src/languages/fr-FR.js
Fixes a typo of `ER_TRY_AGAIN` string in `en-US`, `es-ES` and `fr-FR`.
- en-US.js
- es-ES.js
- fr-FR.js
> Fix typo - ER_TRY_AGAIN string

- src/commands/Images/wholesome.js
- src/languages/en-US.js
- src/languages/es-ES.js
- src/languages/fr-FR.js
- src/languages/it-IT.js
- src/languages/sar-IT.js
Add new command - p!wholesome. This command grabs a random wholesome image from the internet
- Added wholesome.js
- Modified en-US.js
> Add wholesome.js

- src/commands/Developer/eval.js
- src/commands/Developer/exec.js
- src/commands/Moderation/ban.js
- src/commands/Moderation/mute.js
- src/commands/Moderation/softban.js
- src/commands/Music/skip.js
- src/inhibitors/requireMusic.js
Fixes commands that use flags, as flags are now `flagArgs`
- flags > flagArgs
> Fix(flags): flags > flagArgs

- src/commands/Settings/disablecmd.js
Fixes the disableCommand command
- disablecmd.js
> fix: disable command for new klasa sg

- src/commands/Moderation/warn.js
- src/commands/Settings/manageadmin.js
- src/commands/Settings/managedj.js
- src/commands/Settings/managemod.js
- src/commands/Settings/managestaff.js
- src/lib/structures/ModLog.js
Fixes old update methods in settings commands for the new SettingsGateway.
> fix: settings commands for new sg
